# Development environment for streamlit-survey
name: streamlit-survey

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit
    - black
    - isort
    - -e .
